#!/usr/bin/env php
<?php

set_time_limit(0);

(@include_once __DIR__ . '/vendor/autoload.php') || @include_once __DIR__ . '/../../autoload.php';

use Bab\Euler\Command\EulerCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new EulerCommand);
$application->run();
