<?php

namespace Bab\Euler;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not
 * exceed four million, find the sum of the even-valued terms.
 */
class P2 extends Command
{
    protected function configure()
    {
        $this
            ->setName('euler:2')
        ;
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $fibonacci = [1, 2];

        while (true) {
            $last = end($fibonacci);
            $previous = prev($fibonacci);
            $sum = $last + $previous;
            if (4000000 <= $sum) {
                break;
            }
            $fibonacci[] = $sum;
        }

        $output->writeln(sprintf('Found %d numbers', count($fibonacci)));

        $sum = 0;
        foreach ($fibonacci as $value) {
            if (0 === $value % 2) {
                $sum += $value;
            }
        }

        $output->writeln(sprintf('<info>Sum: %d</info>', $sum));
    }
}
